Bv email
StefanoFerrari0/TicketWeb pull request #16
Opened 2021-12-15 22:21 UTC by Benja-cmd

HECHO 
no traer elementos por id objetos con IsDeleted true
mandar las herencias por ID no por NAME
get by ID en tickets
hacer que las tandas tengan stock
traer los tickets segun el vendedor
traer las tandas segun el evento
se agrego "location" al modelo de event para poder enviar el lugar del evento
suma y resta del stock en tandas al vender o eliminar un ticket

2021-12-16 22:57 UTC, StefanoFerrari0 requested changes
Falta hacer unos cambios jejejeje

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/batches.js
> +    const batch = await Batch.findById(batchId)
borrar este

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/batches.js
> +    const addedBatch = await Batch.findByIdAndUpdate(batch, {quantity: batch.quantity+1});
en vez de batch como parametro deberia ser batchId

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/crypt.js
> +    /**/
borrar comentario

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/crypt.js
> +    const secretKey = 'vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3';
esta secret key deberia estar en el ENV

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/crypt.js
> +    const secretKey = 'vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3';
sacar secret key de aquí

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const batchesFound = await Batch.find({ _id: { $in: batches } });
cambiar, ya no se utiliza array

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const batchesFound = await Batch.find({ _id: { $in: batches } });
borrar

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const userFound = await User.find({_id:{$in: user}});
borrar, ya no se utiliza array

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +      user: userFound.map((user)=>user._id),
dejar solo user

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
>        batches: batchesFound.map((batches) => batches._id),
dejar solo batches

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
>      newTicket.email.trim();
borrar ya hace el trim en el modelo

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +  // let results = await OrderModel.find().populate([{path: 'user', select: 'firstname'}, {path: 'meal', select: 'name'}]);
borrar comentario

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    if (ticket.isDelete == true){
sacar el if

2021-12-16 22:57 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const ticket = await Ticket.find({user: user, isDeleted: true});
isDelete: false deberia ser

2021-12-16 22:58 UTC, Benja-cmd commented on server/api/routes/ticket.js
> +const middlewares = require("../../middlewares/index");
lito

2021-12-16 23:00 UTC, Benja-cmd commented on server/api/routes/batches.js
> +router.put("/delete/:batchId", Middleware.isRole("admin"), BatchesController.deleteBatch);
lito

2021-12-16 23:03 UTC, Benja-cmd commented on server/api/routes/batches.js
> +router.get("/get-by-event/:event",BatchesController.getBatchByEvent)
lito

2021-12-16 23:04 UTC, Benja-cmd commented on server/controllers/batches.js
> +      const batchId = req.params.batchId;
lito

2021-12-16 23:04 UTC, Benja-cmd commented on server/controllers/batches.js
> +      const event = req.params.event;
lito

2021-12-16 23:05 UTC, Benja-cmd commented on server/Models/ticketModel.js
> +      type: String,
lito

2021-12-16 23:05 UTC, Benja-cmd commented on server/Models/ticketModel.js
>      qr: {
lito

2021-12-16 23:06 UTC, Benja-cmd commented on server/api/routes/ticket.js
> +router.get("/get-by-user/:user", Middleware.isRole("admin"),TicketController.getUserTicket);
lito

2021-12-16 23:06 UTC, Benja-cmd commented on server/api/routes/ticket.js
> +router.post("/edit/QrCode/:ticketId", TicketController.makeQrCode);
lito

2021-12-16 23:09 UTC, Benja-cmd commented on server/controllers/batches.js
> +        const error = new createHttpError.BadRequest("No se encontro el la relacion de la tanda con el evento.");
litó

2021-12-16 23:11 UTC, Benja-cmd commented on server/controllers/event.js
> +      const userLogged = req.userLogged;
lito

2021-12-16 23:11 UTC, Benja-cmd commented on server/controllers/event.js
> +      const userLogged = req.userLogged;
lito

2021-12-16 23:11 UTC, Benja-cmd commented on server/controllers/event.js
> +      const userId = req.params.userId;
lito

2021-12-16 23:11 UTC, Benja-cmd commented on server/controllers/event.js
> +      const auth = UserService.checkAuth( userLogged, userId);
lito

2021-12-16 23:12 UTC, Benja-cmd commented on server/controllers/ticket.js
> +        qr
lito

2021-12-16 23:12 UTC, Benja-cmd commented on server/controllers/ticket.js
>          qr
listorti

2021-12-16 23:13 UTC, Benja-cmd commented on server/controllers/ticket.js
> +       console.log(ticket);
listrado

2021-12-17 00:12 UTC, Benja-cmd commented on server/controllers/ticket.js
> +        console.log(hash);
listo

2021-12-17 00:22 UTC, Benja-cmd commented on server/controllers/ticket.js
> +      const auth = UserService.checkAuth( userLogged, userId);
listo

2021-12-17 00:24 UTC, Benja-cmd commented on server/controllers/ticket.js
> +      const userLogged = req.userLogged;
listo

2021-12-17 00:25 UTC, Benja-cmd commented on server/controllers/ticket.js
> +        batches,
listo

2021-12-17 00:28 UTC, Benja-cmd commented on server/controllers/ticket.js
> +      const userLogged = req.userLogged;
lito

2021-12-17 00:28 UTC, Benja-cmd commented on server/controllers/ticket.js
> +        const {buyDate, seller, price, email, phone, name, lastName, dni, state, qr, batches, user} = req.body;
lito

2021-12-17 00:29 UTC, Benja-cmd commented on server/controllers/user.js
> +      const auth = UserService.checkAuth( userLogged, userId);
lito

2021-12-17 00:32 UTC, Benja-cmd commented on server/controllers/user.js
>          const error = new createHttpError.BadRequest("Necesita ser admin para acceder a la informacion.");
oka

2021-12-17 00:32 UTC, Benja-cmd commented on server/controllers/user.js
>          const error = new createHttpError.BadRequest("Necesita ser admin para acceder a la informacion.");
listo

2021-12-17 00:35 UTC, Benja-cmd commented on server/controllers/user.js
> +      const userId = req.params.userId;
listo

2021-12-17 00:36 UTC, Benja-cmd commented on server/controllers/user.js
> +      const userLogged = req.userLogged;
ok

2021-12-17 00:36 UTC, Benja-cmd commented on server/controllers/user.js
> +        const error = new createHttpError.BadRequest("Necesita ser admin para acceder a la informacion.");
ok

2021-12-17 00:36 UTC, Benja-cmd commented on server/services/batches.js
> +    const eventFound = await Event.find({ _id: { $in: event } });
ok

2021-12-17 00:36 UTC, Benja-cmd commented on server/services/batches.js
> +      event: eventFound.map((event) => event._id),
ok

2021-12-17 00:39 UTC, Benja-cmd commented on server/services/batches.js
> +    let batch = await Batch.findById(batchId).populate("event").exec();
ok

2021-12-17 00:40 UTC, Benja-cmd commented on server/services/batches.js
> +    console.log(batch.quantity);
ok

2021-12-17 00:40 UTC, Benja-cmd commented on server/services/batches.js
> +    console.log(batchId);
ok

2021-12-17 00:40 UTC, Benja-cmd commented on server/services/event.js
> +  create: async (name, date) => {
ok

2021-12-17 00:41 UTC, Benja-cmd commented on server/services/event.js
> +
ok

2021-12-17 00:42 UTC, Benja-cmd commented on server/services/event.js
> +    let event = await Event.findById(eventId);
ok

2021-12-17 00:42 UTC, Benja-cmd commented on server/services/role.js
> +    if (role.isDelete == true){
ok

2021-12-17 00:42 UTC, Benja-cmd commented on server/services/user.js
> +    if (user.isDelete == true){
ok

2021-12-17 00:44 UTC, Benja-cmd commented on server/services/batches.js
> +    const addedBatch = await Batch.findByIdAndUpdate(batch, {quantity: batch.quantity+1});
ok

2021-12-17 00:44 UTC, Benja-cmd commented on server/services/batches.js
> +    const batch = await Batch.findById(batchId)
ok

2021-12-17 00:44 UTC, Benja-cmd commented on server/services/crypt.js
> +    /**/
ok

2021-12-17 00:44 UTC, Benja-cmd commented on server/services/ticket.js
>        batches: batchesFound.map((batches) => batches._id),
ok

2021-12-17 00:44 UTC, Benja-cmd commented on server/services/ticket.js
>      newTicket.email.trim();
ok

2021-12-17 00:47 UTC, Benja-cmd commented on server/services/ticket.js
> +    const batchesFound = await Batch.find({ _id: { $in: batches } });
ok

2021-12-17 00:54 UTC, Benja-cmd commented on server/services/ticket.js
> +  // let results = await OrderModel.find().populate([{path: 'user', select: 'firstname'}, {path: 'meal', select: 'name'}]);
ok

2021-12-17 00:54 UTC, Benja-cmd commented on server/services/ticket.js
> +    if (ticket.isDelete == true){
ok

2021-12-17 00:54 UTC, Benja-cmd commented on server/services/ticket.js
> +    const ticket = await Ticket.find({user: user, isDeleted: true});
ok

2021-12-17 00:55 UTC, Benja-cmd commented on server/services/ticket.js
> +    const userFound = await User.find({_id:{$in: user}});
ok

2021-12-17 00:56 UTC, Benja-cmd commented on server/services/ticket.js
> +      user: userFound.map((user)=>user._id),
ok

2021-12-17 01:06 UTC, Benja-cmd commented on server/services/crypt.js
> +    const secretKey = 'vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3';
ok

2021-12-17 01:06 UTC, Benja-cmd commented on server/services/crypt.js
> +    const secretKey = 'vOVH6sdmpNWjRRIqCc7rdxs01lwHzfr3';
ok

2021-12-17 13:52 UTC, Benja-cmd commented on server/controllers/ticket.js
> +      const auth = UserService.checkAuth( userLogged, userId);
ok

2021-12-17 15:58 UTC, Benja-cmd commented on server/controllers/ticket.js
> +        const Id = toString(ticket._id);
ok

2021-12-17 20:17 UTC, StefanoFerrari0 requested changes
Por favor no me hagas renegar más, es diciembre y mi salud mental te lo agradeceria, otro PR más así y me mato

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/controllers/ticket.js
> +        const {buyDate, seller, price, email, phone, name, lastName, dni, state, qr, batches, user} = req.body;
No lo sacaste

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/batches.js
>    addQuantity: async (batchId)=>{
para ahorrarte el trabajo de que es lo que no funciona estas tratando de acceder a la propiedad quantity del batchId y sumarle a uno. Nunca va a cosneguir esa información porque es solamente un ID, nada más.

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/event.js
> +    /*const dateNow = new Date();
y esto?

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const ticket = await Ticket.findById({_id: ticketId, isDeleted: false}).populate('batches').exec();
pusiste isDeleted y es isDelete

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/event.js
> +    const event = await Event.findById({_id: eventId, isDeleted: false});
isDeleted no es, es isDelete. Cambiar en todos los getById

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/role.js
> +    const role = await Role.findById({_id: roleId, isDeleted: false});
isDelete

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/role.js
> +  getByRole: async(role)=>{
Se nota que lo copiaste de getByName y no le cambiaste cosas. Por ejemplo la variable name, ni existe ahi, aflojemos al ctrl c y ctrl v y tratemos de escribirlo, la mayoria de tus errores vienen por no prestar atencion a lo que copias, tambien porque no te fijas que subis y tambien porque no lo probas. 
Igualmente para que estaá este servicio, cual es su finalidad, que recibe?

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/ticket.js
> +    const ticket = await Ticket.find({user: userId, isDeleted: false});
isDeleted no, es isDelete

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/user.js
> +    const user = await User.findById({_id: userId, isDeleted: false}).populate('roles').exec();
isDelete

2021-12-17 20:17 UTC, StefanoFerrari0 commented on server/services/user.js
> +    console.log(userLogged);
sacar console.log

2021-12-17 21:46 UTC, StefanoFerrari0 approved these changes
GGWP

2021-12-17 21:47 UTC, merged